global_announcement_channels = ["all-pyama-dev"]

[default_confluence]
domain = "example"
space = "YAS3"
ancestor_id = "12345"

[[services]]
id                     = 1
name                   = "yas3"
incident_team_members  = ["pyama"]
announcement_channels  = ["yas3-alerts"]
confluence = { domain = "example", space = "YAS3-SERVICE1", ancestor_id = "67890" }

[[incident_levels]]
level = 1
description = "サービスに影響が出ている"

[[incident_levels]]
level = 2
description = "サービスにはんぱない影響が出ている"

[[incident_levels]]
level = 3
description = "もうおしまいだ、すべてが終わった"
